[[rulesets]]
group = "ğŸŒŒ YouTube&Twitch&Spotify"
ruleset = "rules/ACL4SSR/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸŒŒ YouTube&Twitch&Spotify"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Twitch.list"

[[rulesets]]
group = "ğŸŒŒ YouTube&Twitch&Spotify"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Spotify.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/ACL4SSR/Clash/ProxyLite.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/DivineEngine/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

