[[rulesets]]
group = "ğŸ¥ YT&Twitch&TikTok&Spotify"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/TikTok.list"

[[rulesets]]
group = "ğŸ¥ YT&Twitch&TikTok&Spotify"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸ¥ YT&Twitch&TikTok&Spotify"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/Twitch.list"

[[rulesets]]
group = "ğŸ¥ YT&Twitch&TikTok&Spotify"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/Spotify.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/Apple.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/DivineEngine/Surge/Ruleset/EpicDownload.list"

[[rulesets]]
group = "ğŸ“º å“”å“©å“”å“©"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/DivineEngine/Surge/Ruleset/StreamingMedia/StreamingSE.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/ProxyLite.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/DivineEngine/Surge/Ruleset/Global.list"

[[rulesets]]
group = "ğŸ® SteamDownload"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/SteamCN.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/DivineEngine/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ifuema/subconverter/master/base/rules/ACL4SSR/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

